name: pytest

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked --group tests

      - name: Run tests
        run: uv run pytest tests
