# Generated by Django 5.2 on 2025-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_image_version_imagevariant_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagevariant",
            name="regenerate",
            field=models.BooleanField(default=False),
        ),
    ]
