# Generated by Django 5.2.7 on 2025-10-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_imagevariant_is_primary_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="is_avif_available",
        ),
        migrations.RemoveField(
            model_name="image",
            name="is_jpegli_available",
        ),
        migrations.RemoveField(
            model_name="image",
            name="is_webp_available",
        ),
        migrations.RemoveField(
            model_name="image",
            name="model_version",
        ),
        migrations.RemoveField(
            model_name="imagevariant",
            name="regenerate",
        ),
        migrations.DeleteModel(
            name="ImageVariantTask",
        ),
    ]
